### ISSUE TITLE
CORS 이슈가 있는뎅.. 

### ISSUE THREAD

**Issue by JehyeongAndYena** [JehyeongAndYena/JehyeongAndYena.github.io#2]
jehyeongandyena.github.io/:1 Access to script at 'https://kit.fontawesome.com/abb467cae5.js' from origin 'https://jehyeongandyena.github.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

깨동아부님 추가해주신 이모티콘(?)들이 잘 뜨지 않아서 ㅠ,ㅠ 개발자도구로 확인해보니 이런 CORS 에러가 발생하구 있는데 추가로 뭔가 조치해주어야 할게 있을까영 
@gaethug

**Comment by gaethug** [comment]
@JehyeongAndYena 
오호... 
fontawesome 쪽에 jehyeongandyena.github.io 도메인을 추가했습니다!

**Comment by JehyeongAndYena** [comment]
> 

우와 ㅠㅠ 넘 감사합니다 !

**Comment by gaethug** [comment]
ㄷ ㄷ 정말 대단하십니다 
혹시 잘 안풀리는 이슈 있으면 태그 걸어주세요
