### ISSUE TITLE
계좌번호 복사 레이어팝업 필요해요

### ISSUE THREAD

**Issue by JehyeongAndYena** [JehyeongAndYena/JehyeongAndYena.github.io#3]
<img width="377" alt="스크린샷 2022-06-20 오후 7 30 55" src="https://user-images.githubusercontent.com/104891105/174583123-60983dba-95e8-4b73-a896-7a0149baf20c.png">

이런식으로 선물박스 눌렀을때 팝업 뜨면서 은행 + 계좌번호
복사하기버튼 / 닫기 버튼 뜨게 해주세여.. 

@antop-dev

**Comment by antop-dev** [comment]
다시 생각해보니까 구지 팝업 띄워서 할 필요까진 없을 것 같네요.

![image](https://user-images.githubusercontent.com/25427395/174626348-5297735d-14dc-4088-91e3-c00a20b69df8.png)

**Comment by gaethug** [comment]
다이얼로그 띄우면 depth?가 한번 더 증가하는것 같기는 한데 
명시적으로 복사하는 느낌이 들어서 좋을것 같기도 하고 그러네요 
마음 바뀌면 말씀해주세요~~ 한번 해볼께요
