### ISSUE TITLE
카카오톡 공유하기가 터치가 잘 안먹어유..

### ISSUE THREAD

**Issue by JehyeongAndYena** [JehyeongAndYena/JehyeongAndYena.github.io#4]
카톡 공유하기가 모바일 기기에서 터치했을때 a tag가 제대로 안먹히는건지 여러번 눌러야 한번 뜨는 현상이 있는뎅
혹시 이유를 아시는분..ㅠ,ㅠ

**Comment by gaethug** [comment]
pc에서도 버튼을 두번 클릭해야 동작하는거 같던데 

혹시 이거 한번 참고해보시겠어요 

https://github.com/JehyeongAndYena/JehyeongAndYena.github.io/pull/5 

@JehyeongAndYena

**Comment by JehyeongAndYena** [comment]
오 ㅠㅠㅠㅠ 이제 너무 잘돼요 ㅠㅠㅠ!!! 진짜 최고시다 
감사합니다 깨동아부님 ㅠ,ㅠ 조만간 깨동이 간식과 함께 뵈어요 🙇🏻‍♀️🦁
